QDRANT_URL = "http://localhost:6333"
COLLECTION_NAME = "legal_knowledge"
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
SUMMARIZATION_MODEL = "google-t5/t5-small"
QA_MODEL = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
