QDRANT_URL = "http://localhost:6333"
COLLECTION_NAME = "legal_knowledge"
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
SUMMARIZATION_MODEL = "google-t5/t5-small"
QA_MODEL = "deepset/minilm-uncased-squad2"
